Connected to MySQL Server:  5.5.5-10.4.27-MariaDB
Login
Connected to MySQL Server:  5.5.5-10.4.27-MariaDB
Wrong credentials
Wrong credentials
Wrong credentials
no account
encrypted
Error while connecting to MySQL TCP/IP port number should be an integer
encrypted
Connected to MySQL Server:  5.5.5-10.4.27-MariaDB
Login
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 203, in button_click
    self.headerLogo = ctk.CTkImage(Image.open(i[29]),
                                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\venv\Lib\site-packages\PIL\Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/xampp/htdocs/SMART-ID-REGISTRATION-MODULE-v2/img/Sad-pug.jpg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 226, in logout
    self.main()
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 285, in main
    self.main()
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 299, in main
    self.main()
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\Desktop\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 253, in main
    if bool(self.login.app.winfo_exists()) and self.login.authenticated:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Intern Dev.DESKTOP-R4CII67\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1139, in winfo_exists
    self.tk.call('winfo', 'exists', self._w))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: can't invoke "winfo" command: application has been destroyed
